### ISSUE TITLE
Access to uninitialized memory

### ISSUE THREAD

**Issue by rbran** [dfsp-spirit/neuroformats-rs#3]
https://github.com/dfsp-spirit/neuroformats-rs/blob/4235e974391863c2f070821cd7294015fee7ff93/src/fs_annot.rs#L195-L208

The function `Vec::with_capacity` pre-allocate the memory, but the memory is uninitialized and can't be read/write directly, it need to be initialized with a function like `Vec::push`, in this case accessing the uninitiated entry at line 203 will cause a panic or UB.

**Comment by rbran** [comment]
Fixed at #5 in https://github.com/dfsp-spirit/neuroformats-rs/pull/5/commits/e26411b847ba1180fd2d11e96c6cce9957776ef2

**Comment by dfsp-spirit** [comment]
Yes, correct. Thanks for reporting and providing a PR.
