### ISSUE TITLE
In vec32minmax use iterators to avoid clone/sort a vector

### ISSUE THREAD

**Issue by rbran** [dfsp-spirit/neuroformats-rs#4]
https://github.com/dfsp-spirit/neuroformats-rs/blob/4235e974391863c2f070821cd7294015fee7ff93/src/util.rs#L67-L79

There are multiple ways to accomplish that, the most elegant ones, use iterators.

The most obvious solution is to use the `Iterator::min` and `Iterator::max`, although it will not filter/panic on NaNs.

I'll work in a solution using iterators and submit a PR soon.

**Comment by rbran** [comment]
While rewriting the function I also noticed a bug in this function:

https://github.com/dfsp-spirit/neuroformats-rs/blob/4235e974391863c2f070821cd7294015fee7ff93/src/util.rs#L99

This line will never be executed, because `has_nan` is always false if `remove_nan` is false.

**Comment by rbran** [comment]
Fixed at #5 in https://github.com/dfsp-spirit/neuroformats-rs/pull/5/commits/63e63367cf17a60e9ae0d5d52b32a8ef177b30d7

**Comment by dfsp-spirit** [comment]
Thanks for reporting and providing a PR.
